scheduleHorizonSeconds: 120
zookeeperTimeoutMs: 5000
master: zk://localhost:2181/mesos
mailUser: "AWSACCESSKEY"
mailPassword: "AWSSECRET"
mailServer: "email-smtp.us-east-1.amazonaws.com:25"
mailFrom: "alerts@yourcompany.com"

http:
    rootPath: /scheduler/*
    adminPort: 4401
    port: 4400

logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: WARN

  loggers:

    "com.airbnb.scheduler": TRACE

  file:

      # If true, write log statements to a file.
      enabled: true

      # Do not write log statements below this threshold to the file.
      threshold: ALL

      # The file to which current statements will be logged.
      currentLogFilename: /tmp/chronos-1.log

      # When the log file rotates, the archived log will be renamed to this and gzipped. The
      # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
      # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
      archivedLogFilenamePattern: ./logs/example-%d.log.gz

      # The number of archived files to keep.
      archivedFileCount: 5

      # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
      timeZone: UTC